In [1]:
import numpy as np

In [2]:
l = [1,2,3]
l

[1, 2, 3]

In [4]:
arr = np.array(l)
print(arr.shape)
arr

(3,)


array([1, 2, 3])

# Expand dimension
1. expand dimension in the position of newaxis, which is an alias for 'None'
2. Use exampand_dims

In [7]:
print(arr[:,np.newaxis].shape)
arr[:,None] 

(3, 1)


array([[1],
       [2],
       [3]])

In [8]:
print(arr[None, :].shape)
arr[None, :] 

(1, 3)


array([[1, 2, 3]])

In [9]:
# add axis along the row
np.expand_dims(arr, axis=0)

array([[1, 2, 3]])

In [10]:
# add second position axis
np.expand_dims(arr, axis=1)

array([[1],
       [2],
       [3]])

# reshape

In [30]:
arr = np.array([[1,2],[3,4],[2,5]])
print(arr.shape)
arr

(3, 2)


array([[1, 2],
       [3, 4],
       [2, 5]])

In [31]:
# flatten
print(arr.reshape(-1).shape)
arr.reshape(-1)

(6,)


array([1, 2, 3, 4, 2, 5])

In [29]:
print(arr.reshape((2,3)).shape)
arr.reshape((2,3))

(2, 3)


array([[1, 2, 3],
       [4, 2, 5]])

In [34]:
arr2 = arr.reshape((3,2,1))
print(arr2.shape)
arr2

(3, 2, 1)


array([[[1],
        [2]],

       [[3],
        [4]],

       [[2],
        [5]]])

In [35]:
# flatten again
arr2.reshape(-1)

array([1, 2, 3, 4, 2, 5])

In [64]:
# or use flatten
arr2.flatten()

array([1, 2, 3, 4, 2, 5])

# Mean, Variance

In [16]:
arr = np.array([[1,2],[3,4],[2,5]])
print(arr)
arr.shape

[[1 2]
 [3 4]
 [2 5]]


(3, 2)

In [60]:
# not along any axis
print(np.mean(arr))
print(np.sum(arr))

2.8333333333333335
17


In [15]:
# mean along the row. row dimension disappears
print(arr.mean(axis=0))
print(np.mean(arr, axis=0))

[2.         3.66666667]
[2.         3.66666667]


In [18]:
# along the col
print(arr.mean(axis=1))
print(np.mean(arr, axis=1))

[1.5 3.5 3.5]
[1.5 3.5 3.5]


In [19]:
# variance along the row
print(arr.var(axis=0))
print(np.var(arr, axis=0))

[0.66666667 1.55555556]
[0.66666667 1.55555556]


In [21]:
# variance along the column
print(arr.var(axis=1))
print(np.var(arr, axis=1))

[0.25 0.25 2.25]
[0.25 0.25 2.25]


# Concatenation
The other dimension has to match

In [22]:
arr

array([[1, 2],
       [3, 4],
       [2, 5]])

In [42]:
# concatenate along row (1st dimension)
y = np.array([6,7]).reshape(1, len(y))
print(y)
np.concatenate((arr, y), axis=0)

[[6 7]]


array([[1, 2],
       [3, 4],
       [2, 5],
       [6, 7]])

In [40]:
# concatenate along column (2nd dimension)
y = np.array([6,7,8]).reshape((len(y), 1))
print(y)
np.concatenate((arr, y), axis=1)

[[6]
 [7]
 [8]]


array([[1, 2, 6],
       [3, 4, 7],
       [2, 5, 8]])

In [101]:
# concatenate a list of arrays will remove the structure
list_arr1 = [np.array([1, 2]),np.array([2, 4]),np.array([3, 5])]
np.concatenate(list_arr1)

array([1, 2, 2, 4, 3, 5])

In [95]:
list_arr2 = [[np.array([1, 2]),np.array([2, 4])], [np.array([3, 5]), np.array([4, 4])]]
np.concatenate(list_arr2)

array([[1, 2],
       [2, 4],
       [3, 5],
       [4, 4]])

In [96]:
np.array(list_arr2)

array([[[1, 2],
        [2, 4]],

       [[3, 5],
        [4, 4]]])

# Sample

In [49]:
np.arange(3)

array([0, 1, 2])

In [47]:
# sample 2 points from a with individual probabilities p
x = np.random.choice(a=[1,2,3,4],  # array or int. If int, np.arange(n)
                     size=2,  # default is None, where a sample is returned
                     replace=True, 
                     p=[0.1, 0.2, 0.5, 0.2])  # assumes uniform distribution if not given
print(x.shape)
x

(2,)


array([4, 2])

# Broadcasting
rules: When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (last) dimensions and works its way forward. Two dimensions are compatible when
1. they are equal, or
2. one of them is 1 (dimensions with size 1 are stretched or “copied” to match the other)

In [51]:
arr2 # 3, 2, 1

array([[[1],
        [2]],

       [[3],
        [4]],

       [[2],
        [5]]])

In [56]:
# 3 * 2 * 1  and
#         2 results in
# 3 * 2 * 2
y = np.array([2, 3])
arr2*y

(2,)


array([[[ 2,  3],
        [ 4,  6]],

       [[ 6,  9],
        [ 8, 12]],

       [[ 4,  6],
        [10, 15]]])